feat: add FieldElement trait and use generic type
vimwitch/rstark pull request #6
Opened 2023-11-10 20:52 UTC by joyqvq

2023-11-11 00:01 UTC, vimwitch requested changes
Really good stuff. I think the remaining changes to this PR will only involve the `Field` and `FieldElement` files. We can take all the basic arithmetic logic in the `Field` class and move it to the `FieldElement` itself. The `FieldElement` will need to know either the `Field` or just the prime to do this.

To avoid having state in the `FieldElement` we could have the basic arithmetic functions take the prime as an input like `fn add(&self, v: &Self, p: &Self)`. Then we have the `Field` class proxy the calls to the `FieldElement` classes by adding the prime as an argument (so the `Field` interface stays the same) like


Field:

```rust
fn add(&self, v1: &FieldElement, v2: &FieldElement) -> FieldElement {
  v1.add(v2, &self.p)
}
```

BigIntElement

```rust
fn add(&self, v: &Self, p: &Self) -> FieldElement {
  (self + v) % p
}
```

Then the subtraction/negation/modd/other functions would never accept or return negative numbers.

2023-11-11 00:08 UTC, vimwitch commented on src/lib.rs
> +    fn add(&self, v: &Self) -> Self {
Disregard most of this, i think the proxy approach described in the root comment is better.

2023-11-14 23:01 UTC, joyqvq commented on src/lib.rs
> +pub struct BigIntElement(pub BigInt);
yeah this way we can implement a trait for this type definition ( rust doesnt allow implement a trait for an external type). in the future if we want to replace with something else, we just put a wrapper around it and let the wrapper impl the trait

2023-11-19 00:50 UTC, joyqvq commented on src/lib.rs
> +            panic!("invalid bigint digits len for u32 conversion");
there was a typo, revised! as a next step i want to examine all panics and remove as much as possible

2023-11-19 04:08 UTC, vimwitch requested changes
Looks great, just a couple small things.

I have modular multiplication working on the gpu and it's already faster than the cpu for batches >= 1024. We could add a `batch_mul` function to the number trait and start looking for places in the code to use it (in a different pr ofc). I think that's a simple starting approach we can use for testing, then we can start integrating more bespoke shaders in the system.

2023-11-19 04:08 UTC, vimwitch commented on src/polynomial.rs
>                  // bring the values into the field using simple arithmetic
These comments can be removed

2023-11-19 04:08 UTC, vimwitch commented on src/lib.rs
> +            println!("modd: {:?}", &self.0);
Is this codepath ever being run? I'd be okay with a panic here if we're not using it.

2023-11-19 22:31 UTC, joyqvq commented on src/lib.rs
> +            println!("modd: {:?}", &self.0);
this is used as a helper function for 
```
fn sub(&self, v: &Self, p: &Self) -> Self {
        BigIntElement(&self.0 + &v.0).modd(p)
    }
```
so it prob should be kept, removed println

2023-11-22 02:21 UTC, merged